<?php

namespace AppBundle\Repository;

/**
 * DeskCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeskCommentRepository extends \Doctrine\ORM\EntityRepository
{
}
