<?php

namespace AppBundle\Repository;

/**
 * FilelistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilelistRepository extends \Doctrine\ORM\EntityRepository
{
}
