<?php

namespace AppBundle\Repository;

/**
 * LDKRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LDKRepository extends \Doctrine\ORM\EntityRepository
{
}
