<?php

namespace AppBundle\Repository;

/**
 * RoomsTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomsTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
