app_rooms:
    resource: "@AppBundle/Controller/RoomsController.php"
    type:     annotation

app_rooms:
    resource: "@AppBundle/Controller/RoomsController.php"
    type:     annotation

app_rooms:
    resource: "@AppBundle/Controller/RoomsController.php"
    type:     annotation

j_bnb_api:
    resource: "@jBnbApiBundle/Controller/"
    type:     annotation
    prefix:   /api_test
api:
    resource: '.'
    type:     'api_platform'
    prefix:   '/apii'
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   '/'

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
