app_rooms:
    resource: "@AppBundle/Controller/RoomsController.php"
    type:     annotation

j_bnb_api:
    resource: "@jBnbApiBundle/Controller/"
    type:     annotation
    prefix:   /api_test
api:
    resource: '.'
    type:     'api_platform'
    prefix:   '/api'
app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
