# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
# app/config/services.yml
    app.service.curl_request:
        class: AppBundle\Service\CurlRequest
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

    admin.rooms:
        class: AppBundle\Admin\RoomsAdmin
        arguments: [~, AppBundle\Entity\Rooms, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Rooms }
    admin.users:

        class: AppBundle\Admin\UsersAdmin


        arguments: [~, AppBundle\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Users }
